name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install libreadline-dev
      run: sudo apt update && sudo apt install -y libreadline-dev build-essential

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile nob
      run: gcc -o nob nob.c

    - name: Compile program
      run: ./nob

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/calc
      if: startsWith(github.ref, 'refs/tags/')
